### ISSUE TITLE
installing packages

### ISSUE THREAD

**Issue by mynameisvinn** [SayreBlades/dask-ecs#6]
is there a better way to install packages/dependencies? (without updating requirements.txt)

for example, for spark, to push packages to nodes in a cluster, you can do something like 
```
from pyspark import SparkContext
sc = SparkContext("local", "App Name", pyFiles=['foo.py', 'bar.py'])
```

**Comment by SayreBlades** [comment]
Thats a pretty cool feature.  I havent seen anything like that in dask.  Dask will handle single function serialization with cloudpickle.  But module/package serialization... I havent seen that.

Ok, cool this is an interesting use case.  Ad-hoc module deploy.  Given dask lack of support, deploying via docker is the only thing that comes to mind.  Let me investigate a bit though.

**Comment by mynameisvinn** [comment]
on second thought, if we want to be as stateless as possible, serializing/distributing functions through cloudpickle should be "good enough".

**Comment by SayreBlades** [comment]
Ok closing this for now but lets file it under the #usability first principle, which needs to be constantly evaluated.
